{{- if .Values.storageClassName }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClassName }}
    {{- if .Values.isDefaultStorageClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: {{ .Values.driverName }}
allowVolumeExpansion: true
volumeBindingMode: {{ .Values.storageClassVolumeBindingMode | default "Immediate" }}
{{- end }}
